<a href="https://colab.research.google.com/github/raimandabishek/Machine-learning/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY

In [3]:
#Numpy Tutorials
#NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

#What is an arrayimport seaborn as sns

#An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [4]:
## initially Lets import numpy

import numpy as np

In [5]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [6]:
print(arr)


[1 2 3 4 5]


In [7]:
type(arr)


numpy.ndarray

In [19]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr1=np.array([my_lst1,my_lst2,my_lst3])

In [20]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [21]:
arr.shape

(5,)

In [22]:
#Indexing
## Accessing the array elements
arr

array([1, 2, 3, 4, 5])

In [23]:
arr

array([1, 2, 3, 4, 5])

In [24]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [25]:
arr

array([1, 2, 3, 4, 5])

In [26]:
arr[3]

np.int64(4)

In [27]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [28]:
arr1[1:,:2]

array([[2, 3],
       [9, 7]])

In [29]:
arr1[1:,2:]

array([[4, 5, 6],
       [6, 8, 9]])

In [33]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [34]:
arr


array([1, 2, 3, 4, 5])

In [35]:
arr[3:]=100


In [36]:
arr

array([  1,   2,   3, 100, 100])

In [38]:
### Some conditions very useful in Exploratory Data Analysis

val=2

arr[arr<3]

array([1, 2])

In [39]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [46]:
arr2=np.arange(0,12).reshape(2,6)


In [47]:
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [49]:
np.ones((2,5),dtype=int)


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [50]:
np.random.rand(3,3)


array([[0.26715168, 0.18008886, 0.08658145],
       [0.65849772, 0.85032425, 0.95336141],
       [0.45096979, 0.00815387, 0.61543877]])

In [51]:
arr_ex=np.random.randn(4,4)


In [52]:
arr_ex

array([[ 0.26867705, -1.06346211,  0.17551856,  0.82240523],
       [-1.28991584, -1.23080402,  0.14940697,  0.63982372],
       [-1.04542716,  1.24241771,  0.18822345, -1.93529865],
       [ 0.09257887,  0.67249702,  1.11999288, -1.28688202]])

In [56]:
np.random.randint(0,100,8).reshape(4,2)


array([[59, 14],
       [99, 82],
       [10, 21],
       [67, 93]])

In [58]:
np.random.random_sample((1,5))


array([[0.97658114, 0.07795205, 0.49812183, 0.65997177, 0.95507558]])